---
x-spark-common: &spark-common
  image: bitnami/spark:3.5.3
  volumes:
      - ./spark/jobs:/opt/bitnami/spark/jobs
      - ./spark/data:/opt/bitnami/spark/data
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: Worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 2g
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_AUTH_SECRET: "test-key"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8081"]
    interval: 1m
    timeout: 10s
    retries: 3
  networks:
    - confluent


services:
  database:
    image: 'postgres:15'
    container_name: 'database'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Password
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
      - "./postgres/init/:/docker-entrypoint-initdb.d"
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dbt:
    container_name: dbt
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.2 
    build: dbt_project/
    volumes:
      - ./dbt_project:/usr/app/dbt
    ports:
      - "8081:8080"
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
      DBT_TARGET: dev
    depends_on:
      - database
    command: ["run"]

  spark-master:
    image: bitnami/spark:3.5.3
    volumes:
      - ./spark/jobs:/opt/bitnami/spark/jobs
      - ./spark/data:/opt/bitnami/spark/data
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      SPARK_AUTH_SECRET: "test-key"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - confluent
  
  spark-worker-1:
    <<: *spark-common
  spark-worker-2:
    <<: *spark-common
  spark-worker-3:
    <<: *spark-common
  spark-worker-4:
    <<: *spark-common

networks:
  confluent:
  